zip 로그확인

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -34,7 +34,7 @@ jobs:
 
       - name: zip create
         # zip 파일을 만듭니다(파일명은 자유, 대신 아래 workflow에 적을 파일명과 동일하게 맞춰주세요).
-        run: zip -r ./build-fe.zip .
+        run: zip -r ./build-fe.zip . || { echo 'Failed to create zip'; exit 1; }
         shell: bash
 
       - name: Configure AWS credentials
